TARGET = mediamtx
PACKAGE = streamserver
VERSION = 1.9.3
SECTION = base
PRIORITY = optional
ARCHITECTURE = arm64
DEPENDS = 
MAINTAINER = bearz <jassimxiong@gmail.com>
DESCRIPTION = This is a stream server.
SERVICE = streamserver.service
